---
- hosts: localhost
  remote_user: ubuntu
  become: true
  gather_facts: false
  tasks:
  - name: clear the environment
    file: 
     name: petclinic.war
     state: absent
  - name: download package from artifactory server
    command: wget http://34.93.116.104:8081/artifactory/repo1/petclinic.war

- hosts: appservers
  remote_user: ubuntu
  become: true
  gather_facts: false
  tasks:
  - name: deploy war file to server
    copy: 
     src: /home/ubuntu/petclinic.war 
     dest: /opt/tomcat/webapps/petclinic.war
  - name: start app server
    command: sh /opt/tomcat/bin/catalina.sh start
