---
- hosts: appserver
  tasks:
  - name: install dbserver
    apt: name={{package_name}} state=latest
  - name: ensure dbserver is running
    service: name={{service_name}} state=running


    #- hosts: webserver
    #  roles:
    #  - webserver
    # - firewall   
